# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "423fe79849f6bfd8a6272b8594104375"
name = "untreepl-flair"
application_url = "https://untreepl-flair-400860611903.us-central1.run.app"
embedded = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_fulfillments,read_inventory,read_locations,read_markets_home,read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://untreepl-flair-400860611903.us-central1.run.app/auth/callback"
]


