# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6fa5894f3e186ab9258d18b66d8cf2c"
name = "untreepl"
application_url = "https://untreepl-400860611903.us-central1.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_markets_home,read_orders,read_products,write_fulfillments,write_products"

[auth]
redirect_urls = [
  "https://untreepl-400860611903.us-central1.run.app/auth/callback",
  "https://untreepl-400860611903.us-central1.run.app/auth/shopify/callback",
  "https://untreepl-400860611903.us-central1.run.app/api/auth/callback"
]
